### ISSUE TITLE
Use stock specific functions from oms-api package

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/shopify-admin-helper#19]
## What is the motivation for adding/enhancing this feature?

We can use the methods for fetching the stock using oms package, and hence we always have the same structure for the response.

## What are the acceptance criteria?

- [ ] Use the methods for fetching stock using oms package
- [ ] Update the usage of stock module as per the structure from the oms package

## Can you complete this feature request by yourself?

- [x] YES
- [ ] NO

**Comment by Dhiraj1405** [comment]
Not required for now. Hence closing
