### ISSUE TITLE
 Enable pickup location search by keyword

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/shopify-admin-helper#24]
## What is the motivation for adding/enhancing this feature?
Users should be allowed to search for pickup locations by name or nearby area(keyword). This will eliminate the need for users to enter the exact zipcode for the pickup location, making the order creation process more user-friendly and efficient.

## What are the acceptance criteria?
Pickup location can be searched by name or nearby area(keyword)
- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- NO

**Comment by ymaheshwari1** [comment]
Closing as already handled.
