### ISSUE TITLE
Optimize image performance with CDN compatible plugin

### ISSUE THREAD

**Issue by dt2patel** [hotwax/shopify-admin-helper#27]
## What is the motivation for adding/enhancing this feature?

Use the new Shopify CDN compatible image component to fetch optimized images from Shopify instead of full size images.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by sanskar345** [comment]
In this app, we have not used any Image component so there is nothing to change.
