### ISSUE TITLE
Select any facility when Store Pickup option is selected

### ISSUE THREAD

**Issue by Chinmay2107** [hotwax/shopify-admin-helper#39]
## Current behavior
When the user selects Store Pickup method for the draft order and selects a facility, it gets selected successfully. But on changing the facility again and trying to select the initial facility on the 3rd try the "Save Changes" button remains in the disabled state.

## Expected behavior
Users should be able to select any of the available facilities at any time.

## Steps to reproduce the issue
Find here the Jam link to reproduce the issue: https://jam.dev/c/a782eb46-3d00-4619-a93c-8fb9d817b731

## Can you handle fixing this bug by yourself?

- [ ] NO

## Environment details
- Browser: Google Chrome, 126
- OS: Ubuntu 22.04 LTS
- Code Version: 1.4.0

**Comment by ymaheshwari1** [comment]
Closing as completed
